# Generated by Django 3.2.3 on 2022-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
